# Generated by Django 3.0.3 on 2020-03-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='pub_date',
            field=models.DateTimeField(max_length=100, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
