# Generated by Django 3.0.3 on 2020-03-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200301_1820'),
        ('app', '0002_auto_20200301_2100'),
    ]

    operations = [
    ]
