# Generated by Django 3.0.3 on 2020-02-18 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_request_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='random',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
