# Generated by Django 3.0.3 on 2020-03-02 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20200301_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='tutors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
