# Generated by Django 3.0.3 on 2020-02-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_request_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='field',
        ),
    ]
