# Generated by Django 3.0.3 on 2020-02-23 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_request_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
