# Generated by Django 3.0.3 on 2020-02-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200223_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
