# Generated by Django 3.0.3 on 2020-02-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200223_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tutor_mode',
        ),
    ]
