# Generated by Django 3.0.3 on 2020-02-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200223_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tutor_mode',
        ),
    ]
