# Generated by Django 3.0.3 on 2020-02-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
