# Generated by Django 3.0.3 on 2020-02-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200226_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_active_request',
            field=models.BooleanField(default=False),
        ),
    ]
