# Generated by Django 3.0.3 on 2020-02-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_user_has_active_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='location',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
