# Generated by Django 3.0.3 on 2020-02-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200228_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
