# Generated by Django 3.0.2 on 2020-03-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200228_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tutors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
