# Generated by Django 3.0.2 on 2020-03-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_request_tutors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='tutors',
        ),
        migrations.AddField(
            model_name='request',
            name='tutors',
            field=models.ManyToManyField(to='app.Tutor'),
        ),
    ]
