# Generated by Django 3.0.2 on 2020-03-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200301_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
