# Generated by Django 3.0.2 on 2020-03-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200301_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='tutors',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
